project:
  type: website
  output-dir: docs
  

website:
  page-navigation: true
  title: "Kundan Kumar"
  description: "Research Scientist"
  site-url: https://kundan-kumarr.github.io
  favicon: misc/info/favicon.png
  repo-url: https://github.com/kundan-kumarr/kundan-kumarr.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Kundan Kumar"
    right: 
      - icon: github
        href: https://github.com/kundan-kumarr/kundan-kumarr.github.io

  navbar: 
    #background: light
    background: "#A9CCE3"
    search: true
    right: 
      - text: About
        icon: person-circle
        href: about_me.qmd
      - text: CV
        icon: file-earmark-text-fill
        href: cv.qmd
        
      - text: "Research"
        icon: lightbulb-fill
        href: rpkg/rpkg.qmd
    #  - text: Research1
      #  menu:
       #   - text: List of Publications
       #     href: publications.qmd
        #  - text: Selected Papers
        #    href: posts.qmd#category=paper
         # - text: Grants
        #    href: projects.qmd 
      - text: "Projects"
        icon: puzzle-fill
        menu:
        - text: "✨ All Projects"  # Main projects page
          href: projects/projects.qmd
        - text: "---"          # Divider (optional)
        - text: "Large Language Models"
          href: projects/projects.qmd
        - text: "Deep Reinforcement Learning"
          href: projects/drl.qmd
        - text: "Deep/Machine Learning"
          href: projects/dl.qmd
        - text: "Statistics"
          href: projects/stat.qmd
        - text: "Computer Vision"
          href: projects/cv.qmd
        - text: "Robotics"
          href: projects/robo.qmd
    
     # - text: "Projects"
    #    href: projects/projects.qmd
      
      - text: "Teaching"
        icon: mortarboard-fill
        href: teaching/teaching.qmd
        
      #- text: "Talks"
      #  icon: mic-fill
        # href: talks/talks.qmd

      - text: "Blogs"
        icon: pen-fill
        href: blog/blog.qmd
        
      #- text: "Publications"
       # icon: journal-bookmark-fill
       # href: publications.qmd
    
     # - text: "About me"
     #   href: about_me.qmd
        
      #- text: "CV"
      #  href: misc/info/CV-CZ-2407.pdf


  google-analytics:
      tracking-id: ""  # Please delete or replace with your own tracking ID
      anonymize-ip: true 
    
bibliography: references.bib

format:
  html:
    theme: styles.scss


